# Generated by Django 2.2.6 on 2019-11-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
                ('sensor', models.FloatField(max_length=200)),
                ('value', models.FloatField(max_length=200)),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
                'ordering': ['value'],
            },
        ),
    ]
